

analyze:
	../../../../utilities/extract_CDS_records.py a_thaliana_ann.fna.gff > a_thaliana.cds.gff
	../../../../utilities/score_TP_FP_FN.py --truth ../../input_files/a_thaliana_ann.fna.CDS.gff --preds a_thaliana.cds.gff > a_thaliana.cds.gff.scored


