

analyze:
	../../utilities/run_analysis_pipeline.py data.json  analysis_dir
	../../utilities/run_analysis_pipeline.py data.wRand.json  analysis_dir_wRand

clean:
	rm -rf ./analysis_dir*
	rm -f ./*.pdf

